controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

states:
    path:       /states
    controller: App\Controller\StateController::getAll
    methods:    GET