controllers:
    resource:   ../src/Controller/
    type:       annotation

kernel:
    resource:   ../src/Kernel.php
    type:       annotation

get_all_states:
    path:       /states
    controller: App\Controller\StateController::getAll
    methods:    GET

get_all_materials:
    path:       /materials
    controller: App\Controller\MaterialController::getAll
    methods:    GET

get_about_us:
    path:       /about-us/{id}
    controller: App\Controller\AboutUsController::getOne
    methods:    GET